// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: storage_service.proto

package apispecproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ApiSpecDocClient is the client API for ApiSpecDoc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApiSpecDocClient interface {
	// Search page of short API specification docs
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Get full API specification
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type apiSpecDocClient struct {
	cc grpc.ClientConnInterface
}

func NewApiSpecDocClient(cc grpc.ClientConnInterface) ApiSpecDocClient {
	return &apiSpecDocClient{cc}
}

func (c *apiSpecDocClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/ApiSpecDoc/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiSpecDocClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/ApiSpecDoc/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApiSpecDocServer is the server API for ApiSpecDoc service.
// All implementations must embed UnimplementedApiSpecDocServer
// for forward compatibility
type ApiSpecDocServer interface {
	// Search page of short API specification docs
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Get full API specification
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedApiSpecDocServer()
}

// UnimplementedApiSpecDocServer must be embedded to have forward compatible implementations.
type UnimplementedApiSpecDocServer struct {
}

func (UnimplementedApiSpecDocServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedApiSpecDocServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedApiSpecDocServer) mustEmbedUnimplementedApiSpecDocServer() {}

// UnsafeApiSpecDocServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApiSpecDocServer will
// result in compilation errors.
type UnsafeApiSpecDocServer interface {
	mustEmbedUnimplementedApiSpecDocServer()
}

func RegisterApiSpecDocServer(s grpc.ServiceRegistrar, srv ApiSpecDocServer) {
	s.RegisterService(&ApiSpecDoc_ServiceDesc, srv)
}

func _ApiSpecDoc_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiSpecDocServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ApiSpecDoc/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiSpecDocServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiSpecDoc_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiSpecDocServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ApiSpecDoc/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiSpecDocServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApiSpecDoc_ServiceDesc is the grpc.ServiceDesc for ApiSpecDoc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApiSpecDoc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ApiSpecDoc",
	HandlerType: (*ApiSpecDocServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _ApiSpecDoc_Search_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ApiSpecDoc_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storage_service.proto",
}
